apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: app2
spec:
  taints:
    - key: workload
      value: "app2"
      operator: "Exists"
      effect: NoSchedule
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ "spot" ]
    - key: "node.kubernetes.io/instance-type"
      operator: NotIn
      values: [ "m6g.16xlarge", "m6gd.16xlarge", "r6g.16xlarge", "r6gd.16xlarge" ]
  limits:
    resources:
      cpu: 50
      memory: 500Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: "cluster-name" # tfvarsで指定したクラスター名を入れる
    securityGroupSelector:
      karpenter.sh/discovery: "cluster-name" # tfvarsで指定したクラスター名を入れる
    tags:
      karpenter.sh/discovery: "cluster-name" # tfvarsで指定したクラスター名を入れる
  ttlSecondsAfterEmpty: 30